name: CI
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tox:
    name: tox
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: install tox
        run: pip install --disable-pip-version-check tox
      - name: run tox
        run: tox
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html # The folder the action should deploy.
          target-folder: .
